global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # EGW Service monitoring
  - job_name: 'egw-service'
    static_configs:
      - targets: ['egw-service:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # EGW Workers monitoring  
  - job_name: 'egw-workers'
    static_configs:
      - targets: ['egw-worker:8001']
    metrics_path: /metrics
    scrape_interval: 15s
    
  # NGINX monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: /nginx_status
    scrape_interval: 30s
    
  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    
  # Node metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # Kubernetes metrics (if deployed in k8s)
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - egw-pipeline
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https
        
  # EGW Pipeline specific metrics
  - job_name: 'egw-pipeline-metrics'
    static_configs:
      - targets: ['egw-service:8000']
    metrics_path: /api/metrics
    scrape_interval: 10s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: '${1}'
      - target_label: job
        replacement: 'egw-pipeline'
        
  # Custom application metrics for performance monitoring
  - job_name: 'egw-performance'
    static_configs:
      - targets: ['egw-service:8000']
    metrics_path: /api/performance/metrics
    scrape_interval: 5s
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'egw_.*'
        action: keep
        
  # Processing queue metrics
  - job_name: 'egw-queue-metrics'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'processing-queue'